import type { NextPage } from 'next'
import Head from 'next/head'
import CollegeSearch from '@/components/CollegeSearch'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>College Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CollegeSearch />
    </div>
  )
}

export default Home
